version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/my-website
    steps:
      - checkout
      - run:
          name: Npm install (node_modules directory)
          command: npm install
      - add_ssh_keys:
          fingerprints:
            - "26:c1:b6:cb:dd:e8:1b:89:99:50:40:9f:09:be:cf:d6"
      - deploy:
          name: Deployment by gulp deploy task
          command: npm run deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build