version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/my-website
    steps:
      - checkout
      - run:
          name: Npm install (node_modules directory)
          command: npm install
      - deploy:
          name: Deployment by gulp deploy task
          command: npm run deploy